//
// Created by david on 11. 12. 2022.
//

#ifndef SYSTEMMONITORINGSERVER_CONSTANTS_H
#define SYSTEMMONITORINGSERVER_CONSTANTS_H

#define S_INT64 8
#define S_CHAR 1
#define WAIT_FOR_READY_READ 120000

// Tests
#define TEST_USERNAME "Test"
#define TEST_PASSWORD "test123"
#define TEST_ID 5
#define TEST_CLIENT_ID 5

#endif //SYSTEMMONITORINGSERVER_CONSTANTS_H
