//
// Created by david on 11. 12. 2022.
//

#ifndef SYSTEMMONITORINGSERVER_CONSTANTS_H
#define SYSTEMMONITORINGSERVER_CONSTANTS_H

#define S_INT64 8
#define S_CHAR 1

#endif //SYSTEMMONITORINGSERVER_CONSTANTS_H
